### PR TITLE
Use macros to templatize search functions

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Feel free to squash and merge if you are okay with these changes.

**Comment by jkoritzinsky** [comment]
Can we change the names of the template files to end with .template.h instead of .template? That will provide a better editor experience by default I think.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Done.

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
